### ISSUE TITLE
nginx config incorrect

### ISSUE THREAD

**Issue by kheimerl** [facebookincubator/CommunityCellularManager#17] opened 2016-12-16 03:17 UTC
As per https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#taxing-rewrites

nginx config ssl redirect should be:

    # Force HTTPS
    if ($http_x_forwarded_proto != "https") {
      return 301 https://$host$request_uri;
    }

**Comment by 9muir** [comment] 2016-12-16 16:05
do you want to just make that a PR? Was that the cause of the double parameter in the query string?

**Comment by kheimerl** [comment] 2016-12-16 17:10
I can make one eventually but i'm in the midst of the whole thing. This was the cause of the double param.

**Comment by 9muir** [comment] 2017-01-12 14:49
Closing, will accept PR once it's available.

**Closed by 9muir** 2017-01-12 14:49 UTC
