### ISSUE TITLE
certifier ansible script missing easyrsa installation

### ISSUE THREAD

**Issue by kheimerl** [facebookincubator/CommunityCellularManager#18] opened 2016-12-16 22:34 UTC
eom

**Comment by 9muir** [comment] 2016-12-19 13:42
are you sure? It looks fine to me:

    TASK [add easyrsa repo] ********************************************************
    changed: [cert] => {"after": "5a429d22c78604c95813b457a8bea565a39793fa", "before": null, "changed": true, "warnings": []}
    
    TASK [copy easyrsa] ************************************************************
    changed: [cert] => {"changed": true, "cmd": ["cp", "/home/vagrant/easyrsa/easyrsa3/easyrsa", "/home/vagrant/certifier/"], "delta": "0:00:00.004870", "end": "2016-12-19 13:38:32.960355", "rc": 0, "start": "2016-12-19 13:38:32.955485", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
    
    TASK [easyrsa permissions] *****************************************************
    ok: [cert] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/home/vagrant/certifier/easyrsa", "size": 35253, "state": "file", "uid": 0}

**Comment by kheimerl** [comment] 2016-12-20 17:11
The prod one, certifier.yml.

**Comment by shaddi** [comment] 2016-12-20 17:21
This is by design. The cert generation used for the development environment isn't a recommended setup for a production deployment, and how one wants to deploy in production is probably going to vary from environment to environment.

What we've done in the past for production environments is generate a root key on a known trusted machine with a good source of randomness (i.e., not on AWS). The root key is stored offline and used only to generate signing key(s), which are then manually copied over to the machine running `certifier` via a secure channel. Then the signing key is used like the root key in the dev environment.

We should copy the easyrsa script and certifier.py over, and if we're not doing that that's a bug. But adding instructions or a script for production-ready key generation, etc, is something we'd have to add.

**Comment by kheimerl** [comment] 2016-12-20 17:23
We are not copying the easyrsa script over and that is a bug.

**Comment by 9muir** [comment] 2017-01-05 02:51
resolved by 8ec79b6

**Closed by 9muir** 2017-01-05 02:51 UTC
